// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbyzutrytqysrrfctalm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ieXp1dHJ5dHF5c3JyZmN0YWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTI1NTksImV4cCI6MjA2NjE4ODU1OX0.GNWFIlvD-mkMrD95tPyeJhtjMNc1tb2cKhz418Cl20o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);